namespace Hexed.SDK.Objects
{
    internal class Enums
    {
        public enum ClassId
        {
            CAI_BaseNPC = 0,
            CAK47,
            CBaseAnimating,
            CBaseAnimatingOverlay,
            CBaseAttributableItem,
            CBaseButton,
            CBaseCombatCharacter,
            CBaseCombatWeapon,
            CBaseCSGrenade,
            CBaseCSGrenadeProjectile,
            CBaseDoor,
            CBaseEntity,
            CBaseFlex,
            CBaseGrenade,
            CBaseParticleEntity,
            CBasePlayer,
            CBasePropDoor,
            CBaseTeamObjectiveResource,
            CBaseTempEntity,
            CBaseToggle,
            CBaseTrigger,
            CBaseViewModel,
            CBaseVPhysicsTrigger,
            CBaseWeaponWorldModel,
            CBeam,
            CBeamSpotlight,
            CBoneFollower,
            CBreakableProp,
            CBreakableSurface,
            CC4,
            CCascadeLight,
            CChicken,
            CColorCorrection,
            CColorCorrectionVolume,
            CCSGameRulesProxy,
            CCSPlayer,
            CCSPlayerResource,
            CCSRagdoll,
            CCSTeam,
            CDEagle,
            CDecoyGrenade,
            CDecoyProjectile,
            CDynamicLight,
            CDynamicProp,
            CEconEntity,
            CEmbers,
            CEntityDissolve,
            CEntityFlame,
            CEntityFreezing,
            CEntityParticleTrail,
            CEnvAmbientLight,
            CEnvDetailController,
            CEnvDOFController,
            CEnvParticleScript,
            CEnvProjectedTexture,
            CEnvQuadraticBeam,
            CEnvScreenEffect,
            CEnvScreenOverlay,
            CEnvTonemapController,
            CEnvWind,
            CFireCrackerBlast,
            CFireSmoke,
            CFireTrail,
            CFish,
            CFlashbang,
            CFogController,
            CFootstepControl,
            CFunc_Dust,
            CFunc_LOD,
            CFuncAreaPortalWindow,
            CFuncBrush,
            CFuncConveyor,
            CFuncLadder,
            CFuncMonitor,
            CFuncMoveLinear,
            CFuncOccluder,
            CFuncReflectiveGlass,
            CFuncRotating,
            CFuncSmokeVolume,
            CFuncTrackTrain,
            CGameRulesProxy,
            CHandleTest,
            CHEGrenade,
            CHostage,
            CHostageCarriableProp,
            CIncendiaryGrenade,
            CInferno,
            CInfoLadderDismount,
            CInfoOverlayAccessor,
            CItem_Healthshot,
            CKnife,
            CKnifeGG,
            CLightGlow,
            CMaterialModifyControl,
            CMolotovGrenade,
            CMolotovProjectile,
            CMovieDisplay,
            CParticleFire,
            CParticlePerformanceMonitor,
            CParticleSystem,
            CPhysBox,
            CPhysBoxMultiplayer,
            CPhysicsProp,
            CPhysicsPropMultiplayer,
            CPhysMagnet,
            CPlantedC4,
            CPlasma,
            CPlayerResource,
            CPointCamera,
            CPointCommentaryNode,
            CPoseController,
            CPostProcessController,
            CPrecipitation,
            CPrecipitationBlocker,
            CPredictedViewModel,
            CProp_Hallucination,
            CPropDoorRotating,
            CPropJeep,
            CPropVehicleDriveable,
            CRagdollManager,
            CRagdollProp,
            CRagdollPropAttached,
            CRopeKeyframe,
            CSCAR17,
            CSceneEntity,
            CSensorGrenade,
            CSensorGrenadeProjectile,
            CShadowControl,
            CSlideshowDisplay,
            CSmokeGrenade,
            CSmokeGrenadeProjectile,
            CSmokeStack,
            CSpatialEntity,
            CSpotlightEnd,
            CSprite,
            CSpriteOriented,
            CSpriteTrail,
            CStatueProp,
            CSteamJet,
            CSun,
            CSunlightShadowControl,
            CTeam,
            CTeamplayRoundBasedRulesProxy,
            CTEArmorRicochet,
            CTEBaseBeam,
            CTEBeamEntPoint,
            CTEBeamEnts,
            CTEBeamFollow,
            CTEBeamLaser,
            CTEBeamPoints,
            CTEBeamRing,
            CTEBeamRingPoint,
            CTEBeamSpline,
            CTEBloodSprite,
            CTEBloodStream,
            CTEBreakModel,
            CTEBSPDecal,
            CTEBubbles,
            CTEBubbleTrail,
            CTEClientProjectile,
            CTEDecal,
            CTEDust,
            CTEDynamicLight,
            CTEEffectDispatch,
            CTEEnergySplash,
            CTEExplosion,
            CTEFireBullets,
            CTEFizz,
            CTEFootprintDecal,
            CTEFoundryHelpers,
            CTEGaussExplosion,
            CTEGlowSprite,
            CTEImpact,
            CTEKillPlayerAttachments,
            CTELargeFunnel,
            CTEMetalSparks,
            CTEMuzzleFlash,
            CTEParticleSystem,
            CTEPhysicsProp,
            CTEPlantBomb,
            CTEPlayerAnimEvent,
            CTEPlayerDecal,
            CTEProjectedDecal,
            CTERadioIcon,
            CTEShatterSurface,
            CTEShowLine,
            CTesla,
            CTESmoke,
            CTESparks,
            CTESprite,
            CTESpriteSpray,
            CTest_ProxyToggle_Networkable,
            CTestTraceline,
            CTEWorldDecal,
            CTriggerPlayerMovement,
            CTriggerSoundOperator,
            CVGuiScreen,
            CVoteController,
            CWaterBullet,
            CWaterLODControl,
            CWeaponAug,
            CWeaponAWP,
            CWeaponBaseItem,
            CWeaponBizon,
            CWeaponCSBase,
            CWeaponCSBaseGun,
            CWeaponCycler,
            CWeaponElite,
            CWeaponFamas,
            CWeaponFiveSeven,
            CWeaponG3SG1,
            CWeaponGalil,
            CWeaponGalilAR,
            CWeaponGlock,
            CWeaponHKP2000,
            CWeaponM249,
            CWeaponM3,
            CWeaponM4A1,
            CWeaponMAC10,
            CWeaponMag7,
            CWeaponMP5Navy,
            CWeaponMP7,
            CWeaponMP9,
            CWeaponNegev,
            CWeaponNOVA,
            CWeaponP228,
            CWeaponP250,
            CWeaponP90,
            CWeaponSawedoff,
            CWeaponSCAR20,
            CWeaponScout,
            CWeaponSG550,
            CWeaponSG552,
            CWeaponSG556,
            CWeaponSSG08,
            CWeaponTaser,
            CWeaponTec9,
            CWeaponTMP,
            CWeaponUMP45,
            CWeaponUSP,
            CWeaponXM1014,
            CWorld,
            DustTrail,
            MovieExplosion,
            ParticleSmokeGrenade,
            RocketTrail,
            SmokeTrail,
            SporeExplosion,
            SporeTrail
        }

        public enum SendPropType
        {
            DPT_Int = 0,
            DPT_Float,
            DPT_Vector,
            DPT_VectorXY, // Only encodes the XY of a vector, ignores Z
            DPT_String,
            DPT_Array,     // An array of the base types (can't be of datatables).
            DPT_DataTable,
            DPT_Int64,
            DPT_NUMSendPropTypes
        }

        public enum Team
        {
            None = 0,
            Spectator = 1,
            Terrorist = 2,
            CounterTerrorist = 3
        }

        public enum PlayerFlag
        {
            OnGround = 1 << 0,
            Ducking = 1 << 1,
            WaterJump = 1 << 2,
            OnTrain = 1 << 3,
            InTrain = 1 << 4,
            Frozen = 1 << 5,
            AtControls = 1 << 6,
            Client = 1 << 7,
            Fakeclient = 1 << 8,
            InWater = 1 << 9
        }

        public enum ItemDefinitionIndex
        {
            DESERT_DEAGLE = 1,
            DUAL_BERRETAS = 2,
            FIVE_SEVEN = 3,
            GLOCK_18 = 4,
            AK_47 = 7,
            AUG = 8,
            AWP = 9,
            FAMAS = 10,
            G3SG1 = 11,
            GALIL_AR = 13,
            M249 = 14,
            M4A4 = 16,
            MAC_10 = 17,
            P90 = 19,
            UMP_45 = 24,
            XM1014 = 25,
            PP_BIZON = 26,
            MAG_7 = 27,
            NEGEV = 28,
            SAWED_OFF = 29,
            TEC_9 = 30,
            ZEUS_X27 = 31,
            P2000 = 32,
            MP7 = 33,
            MP9 = 34,
            NOVA = 35,
            P250 = 36,
            SCAR_20 = 38,
            SG_553 = 39,
            SSG08 = 40,
            DEFAULT_CT = 42,
            FLASHGRENADE = 43,
            HE_GRENADE = 44,
            SMOKE_GRENADE = 45,
            MOLOTOV_GRENADE = 46,
            DECOY_GRENADE = 47,
            INCENDIARY_GRENADE = 48,
            C4 = 49,
            DEFAULT_T = 59,
            M4A1_S = 60,
            USP_S = 61,
            CZ75_AUTO = 63,
            R8_REVOLVER = 64,
            KNIFE_BAYONET = 500,
            KNIFE_FLIP = 505,
            KNIFE_GUT = 506,
            KNIFE_KARAMBIT = 507,
            KNIFE_M9_BAYONET = 508,
            KNIFE_HUNTSMAN = 509,
            KNIFE_FALCHION = 512,
            KNIFE_BOWIE = 514,
            KNIFE_BUTTERFLY = 515,
            KNIFE_SHADOW = 516,
            MAX = 517
        }
    }
}
